package uimap;

import org.openqa.selenium.By;


public class TelenorMobileWithoutSubscription {	
	
	// ListBox
	public static final By lstSelectSubScription = By.xpath("//div[@id='sortinglist']/dl[@class='dropdown']");
	public static final By lstSelectSubScriptionType = By.xpath("//div[@id='sortinglist']/dl[@class='dropdown']//li/a[*/text()='@1@']");
	public static final By lstSelectUtenBinding = By.id("Body_MainContent_productDetail_Subscriptions_ctl00_subscriptionRepeater_DropDownBinding_0");
	
	// links
	public static final By lnkWithoutSubscription = By.xpath("//div[@id='productContainer']//div[@class='product-item']//h2//div[@class='subscriptionNameContainer']/span[@class='currentSubscriptionName']");
	public static final By lnkMobileColor = By.xpath("//div[@class='product-overview']//div[@class='colorselectorbutton']//a");
	public static final By lnkTabs = By.xpath("//div[@class='productDetails']//ul[@class='tabs']//li"); 
	public static final By lnkProductName = By.xpath("//div[@class='group']//table[@id='cart-content']//tbody//tr//td[@class='headcart']//strong//a");
	public static final By lnkNordilogProductName = By.xpath("//div[@class='group']//tr[@class='productgroup']//td[@class='headcart']//strong//a");
	public static final By lnkAcessoriesName = By.xpath("//div[@class='group']//tr[@class='productgroup ']//td[@class='headcart']//strong//a");
	public static final By lnkOrderNumber = By.xpath("//div[@id='completedOrdersSearchResult']//div[@class='row']//ul//li[1]//h4//a");			
	public static final By lnkOrderSearch = By.xpath("//div[@id='header']//div[@id='menu']//ul//li[6]//a");
	public static final By lnkCheckOrderStatus = By.xpath("//div[@id='page']//div[2]//a[3]");
	public static final By lnkFake = By.xpath("//div[@id='context']//div[@class='rows']//div[@class='row']//input[@type='image']");
	public static final By lnkBack = By.xpath("//div[@id='page']//a");
	public static final By lnkCreateAgent = By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Opprett agent')]");
	public static final By lnkNettbutikk = By.xpath("//div[@class='b2b-header_bottom']//ul[1]//li[2]//a[contains(text(),'Nettbutikk')]");
	public static final By lnkTest = By.xpath("//div[@class='list-overview panel ']//ul//li[@class='product ui-draggable']//div[@class='listcontentLarge']//h3//a");
	public static final By lnkCreatePricing =By.xpath("//div[@id='mainmenu']//nav//ul[@id='menu']//li[@class='section'][4]//ul//li[@class='subsection'][2]//a");
	public static final By lnkProduct = By.xpath("//div[@id='headerwrap']//div[@id='mainmenu']//nav//ul[@id='menu']//li[@class='section selected']//a[@class='sub']");
	public static final By lnkaccessories = By.xpath("//div[@class='group']//div[@class='basket-accessories_trigger basket-accessories_trigger--closed'][1]//a[@class='basket-accessories_trigger_link']");
	public static final By lnkRefresh = By.xpath("//div[@class='group']//tr[@class='productgroup']//td[@class='pricecart']//input[@class='quantityRefresh']");
	public static final By lnkaccessoriesTab =By.xpath("//div[@class='productDetails']//li[@id='tilbehorTab']//a");
	public static final By lnkShopMore =By.xpath("//div[@class='basketMoreCash']//div[@class='basketContainer']//div[@class='basketMore']//a[*/text()='Handle mer']");
	public static final By lnkTablets =By.xpath("//div[@id='tabsfacet']//li//a[*/text()='Nettbrett']");
	public static final By lnkBreadCrumb =By.xpath("//div[@id='breadcrumb']//li[3]");
	public static final By lnkMobileName =By.xpath("//div[@id='produktModule']//h1//span");
	public static final By lnkAbonnementTab =By.xpath("//div[@class='productDetails']//ul//li//a[contains(text(),'Abonnement')]");
	public static final By lnkHomeTabs =By.xpath("//div[@id='tabsfacet']//li//a");
	public static final By lnkProductSubscription =By.xpath("//div[@class='row rowcontainer subscriberselection']//span//strong");
	public static final By lnkAddressInformationTab=By.xpath("//div[@id='tabs']//li//a[contains(text(),'Adresseinformasjon')]");
	public static final By lnkPaymentInformationTab=By.xpath("//div[@id='tabs']//li//a[contains(text(),'Betalingsinformasjon')]");
	public static final By lnkTaskTab=By.xpath("//div[@id='header']//div[@id='menu']//ul//li[5]//a[contains(text(),'Tasks')]");
	public static final By lnkTaskGroup=By.xpath("//div[@id='content']//table[8][@class='taskListGroup']//tbody//tr[2]//td[4]//input[@id='Body_ReplaceMainContent_MainContent_RepeaterGroups_RepeaterTasks_7_LinkButton1_0']");
	public static final By lnkStatus=By.xpath("//div[@id='header']//div[@id='menu']//ul//li[2]//a[contains(text(),'Status')]");
	public static final By lnkTaskStatus=By.xpath("//div[@id='taskOverview']//tbody//tr[@class='Successful']//td[contains(text(),'FetchAllSalespoints')]");
	public static final By lnkButtik=By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//ul//li[@class='subsection']//a[contains(text(),'Butikk')]");
	public static final By lnkSearch=By.xpath("//div[@class='filter-smaller']//div[@id='show-search']//input[@id='Search']");
	public static final By lnkAssortment=By.xpath("//div[@class='product'][1]//div[@class='listcontent']//form//input[@name='SeeAssortment']");
	public static final By lnkAlleProdukter=By.xpath("//div[@id='tabs']//ul//li//a[contains(text(),'Alle produkter')]");
	public static final By lnksearchbutton=By.xpath("//div[@class='filter']//div[@id='show-search']//input[@id='searhButton']");
	public static final By lnkbutton=By.xpath("//div[@id='page']//div//input[@id='Body_ReplaceMainContent_Button2']");
	public static final By lnkOrderList=By.xpath("//div[@id='page']//div//p[3]//a");
	public static final By lnkAddProduct=By.xpath("//div[@id='mainmenu']//nav//ul//li[@class='subsection']//a[contains(text(),'Nytt lokalt produkt')]");
	public static final By lnkIncomingProduct=By.xpath("//div[@id='mainmenu']//nav//ul//li[@class='section']//ul//li[@class='subsection']//a[contains(text(),'Innkomne produkter')]");
	public static final By lnkLightBox=By.xpath("//div[@class='main-content']//li//a[@class='lightbox']");
	public static final By lnkCNETSearch=By.xpath("//div[@id='failedOrderFilter']//form[@id='SearchForm']//div//fieldset[@class='container']//input[@id='searchButton']");
	public static final By lnkProductMenu =By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//a[@class='sub' and contains(text(),'Produkt')]");
	public static final By lnkButikkMenu =By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//a[@class='sub' and contains(text(),'Butikk')]");
	public static final By lnkButikkSubMenu =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Butikk')]");
	public static final By lnkNext =By.xpath("//div[@class='next-page']//input[@name='next']");
	public static final By lnkUserMenu =By.xpath("//div[@id='mainmenu']//li[@class='section']//a[@class='sub' and contains(text(),'Bruker')]");
	public static final By lnkUserSubMenu =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Opprett bruker')]");
	public static final By lnkAdministrator =By.xpath("//div[@class='form']//div//table[@class='roles']//tbody//tr//td//input[@value='administrator']");
	public static final By lnkCampaginAttribute =By.xpath("//div[@class='product']//div[@class='listcontent']//form//input[@name='EditCampaignAttributes']");
	public static final By lnkBrowse =By.xpath("//div[@class='img-menu']//div[@class='thumbnail-upload']//table//input[@id='file']");
	public static final By lnkProperties =By.xpath("//div[@class='wizard-steps']//ul//li[2]");
	public static final By lnkCustomerReference =By.xpath("//div[@class='wizard-steps']//ul//li[7]");
	public static final By lnkRoller =By.xpath("//div[@class='wizard-steps']//ul//li[8]");
	public static final By lnkCampaign =By.xpath("//div[@class='main-content']//ul//li[4]//a[contains(text(),'Kampanje')]");
	public static final By lnkCustomer =By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//a[@class='sub' and contains(text(),'Kunder')]");
	public static final By lnkCustomerSubMenu =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Kunder')]");	
	public static final By lnkEditCustomer =By.xpath("//div[@class='product'][1]//div[@class='form']//form[1]//input");
	public static final By lnkCustomerSpecific =By.xpath("//div[@class='wizard-steps']//li[5]");
	public static final By lnkAdminMenu =By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//a[@class='sub' and contains(text(),'Admin')]");
	public static final By lnkAdminSubMenu =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Visningskategorier')]");
	public static final By lnkProductCatalog=By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Produktkatalog')]");
	public static final By lnkAdminSubMenu2 =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Overfør til butikker manuelt')]");
	public static final By lnkLevel3Item =By.xpath("//div[@class='useType functions']//li[last()]//a[contains(text(),'@1@')]");
	public static final By lnkPageMenu =By.xpath("//div[@class='pagemenu']//ul//li[last()-1]");
	public static final By lnkPageCount =By.xpath("//div[@class='pagemenu']//ul//li");
	public static final By lnkPageNumber =By.xpath("//div[@class='pagemenu']//ul//li[@1@]");
	public static final By lnkDeliveryMethod =By.xpath("//div[@class='wizard-steps']//li//a[contains(text(),'Leveringsmetode')]");
	public static final By lnkSupplierMenu =By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//a[@class='sub' and  contains(text(),'Leverandør')]");
	public static final By lnkSupplierSubMenu =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Lag ny')]");
	public static final By lnkAgentMenu =By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//a[@class='sub' and  contains(text(),'Agent')]");
	public static final By lnkAgentSubMenu =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Agent')]");
	public static final By lnkCheckIMEStatus =By.xpath("//div[@id='page']//a[2]");
	public static final By lnkIMEStatus =By.xpath("//div[@id='page']//table//tbody//tr[last()]//td[last()]");
	public static final By lnkProductCat =By.xpath("//div[@class='colgroup']//ul//li//a[contains(text(),'Produkt')]");
	public static final By lnkProdukttekster =By.xpath("//div[@class='wizard-steps']//li[4]//a[contains(text(),'Produkttekster')]");
	public static final By lnkAbonnementstyper =By.xpath("//div[@class='wizard-steps']//li[last()-1]//p");
	public static final By lnkUtvalgMenu =By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//a[@class='sub' and  contains(text(),'Utvalg')]");
	public static final By lnkUtvalgCat =By.xpath("//div[@class='colgroup']//ul//li//a[contains(text(),'Utvalg')]");
	public static final By lnkUtvalgSubMenu1 =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Utvalg')]");
	public static final By lnkUtvalgSubMenu2 =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Opprett utvalg')]");
	public static final By lnkPricing =By.xpath("//div[@class='colgroup']//ul//li//a[contains(text(),'Prising')]");
	public static final By lnkPricingMenu =By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//a[@class='sub' and  contains(text(),'Prising')]");
	public static final By lnkPricingSubMenu =By.xpath("//div[@id='mainmenu']//li[@class='subsection']//a[contains(text(),'Opprett priskalkyle')]");
	public static final By lnkAgent =By.xpath("//div[@class='colgroup']//ul//li//a[contains(text(),'Agent')]");
	public static final By lnkAddIndividualItems =By.xpath("//div[@class='wizard-steps']//li[3]");
	public static final By lnkForHandlerMenu =By.xpath("//div[@id='mainmenu']//ul//li[@class='section']//a[@class='sub' and  contains(text(),'Forhandler')]");
	public static final By lnkForHandlerSubMenu =By.xpath("//div[@id='mainmenu']//ul//li[@class='subsection']//a[contains(text(),'Forhandler')]");
	public static final By lnkStoreStep1 =By.xpath("//div[@class='create-steps']//ul//li[1]//a[contains(text(),'Ikke gjennomført')]");
	public static final By lnkFindCustomer =By.xpath("//div[@class='main-content']//div[@class='form']//a[contains(text(),'Finn kunde')]");
	public static final By lnkStoreStep3 =By.xpath("//div[@class='create-steps']//ul//li[3]//a[contains(text(),'Ikke gjennomført')]");
	public static final By lnkStoreStep4 =By.xpath("//div[@class='create-steps']//ul//li[4]//a[contains(text(),'Ikke gjennomført')]");
	public static final By lnkStoreStep5 =By.xpath("//div[@class='create-steps']//ul//li[5]//a[contains(text(),'Ikke gjennomført')]");
	public static final By lnkButikk =By.xpath("//div[@class='colgroup']//a[contains(text(),'Butikk')]");
	public static final By lnkStoreName =By.xpath("//div[@class='list-products']//div[@class='product'][1]//h3//a");
	public static final By lnkViewCategories =By.xpath("//div[@class='wizard-steps']//ul//li//a[contains(text(),'Visningskategorier')]");
	public static final By lnkMobiltBredbånd =By.xpath("//div[@id='tabsfacet']//li[2]");
	public static final By lnkTextProductPreferences =By.xpath("//div[@class='listcontent']//a[contains(text(),'Tekster og produktinnstillinger for butikk')]"); 
	public static final By lnkTelenorPrivate =By.xpath("//div[@class='wizard-message-info']//a[contains(text(),'Telenor Nettbutikk Privat')]");
	public static final By lnkLogicaStore = By.xpath("//div[@class='list-scroll']//ul//li[contains(text(),'Logica Norge AS')]");
	public static final By lnkSubscriber =By.xpath("//div[@id='ufd-container']//div[2][@class='plain']//div[@class='list-scroll'][1]//ul//li[last()]");
	public static final By lnkSubscriberSharedUser =By.xpath("//div[@id='ufd-container']//div[@class='plain']//div[@class='list-scroll'][1]//ul//li[last()]");
	public static final By lnkbuttonRelease =By.xpath("//div[@id='headerwrap']//div[@class='ident']//a//img");
	public static final By lnkSelectAllChkBox =By.xpath("//div[@class='selector']//li[1]//div[@class='selector_item_body']//div[@class='select-tags'][2]//div[@class='select-tags_actions']//a[@title='Velg alle']");
	public static final By lnkLaunchSimba =By.xpath("//form[@id='form1']//div//a[contains(text(),'Simba')]");
	public static final By lnkUtvalg =By.xpath("//div[@class='content']//div[@class='colgroup']//div[@class='abcdefCol']//ul[@class='path']//li[2]//a[@href='/Selection/ShowList']");
	public static final By lnkCreateNewUtvalg =By.xpath("//div[@class='action-field']//div[@class='action-content']//h5//strong//a");
	public static final By lnkProductVariantUtvalg =By.xpath("//div[@class='main-content']//ul//li[4]//span[2]//a");
	public static final By lnkHandleMer =By.xpath("//div[@id='content']//div[@class='related']//ul//li//a[contains(text(),'Handle mer')]");
	public static final By lnkAgentTitle =By.xpath("//div[@class='list-products']//div[@class='product']//div[@class='listcontentLarge']//h3//a[contains(text(),'@1@')]");
	public static final By lnkAgentSubscriptionChk =By.xpath("//div[@class='dragdrop']//div[@id='selectionList']//div[@class='product']//div[@class='listcontentLarge']//h3//a[1]");
	public static final By lnkSalesProductLink =By.xpath("//div[@class='product']//div[@class='listcontent']//span[contains(text(),'Se utsalgsprodukter')]");
	public static final By lnkSelectSalesProduct =By.xpath("//div[@class='productconnection-list']//div[@class='container']//h5[2]");
	public static final By lnkCheckOrderData = By.xpath("//div[@id='page']//div[2]//a[2]");
	public static final By lnkSharedUserLogin = By.xpath("//div[@class='main-content']//div[2][@class='form']//fieldset//p[5]//span//a");
	public static final By lnkCreateButikkAdmin = By.xpath("//div[@class='form']//p//a[contains(text(),'Lag ny forhandler')]");
	public static final By lnkCart = By.xpath("//div[@class='basketContainer']//div//p//strong//a//span[contains(text(),'Vis handlekurv')]");
	public static final By lnkShopVismer = By.xpath("//div[@class='product'][1]//div[@class='listcontent']//div[@class='form showChildrenOnClick']//a[contains(text(),'Vis mer')]");
	
	// Buttons
	public static final By btnSelectProduct = By.xpath("//div[@id='productContainer']//div[@class='product-item'][@1@]//a//span[contains(text(),'Velg')]");
	public static final By btnAddToBasket = By.xpath("//div[@class='product-overview']//div[@class='button shop-btn']//a");
	public static final By btnCheckOut = By.xpath("//div[@class='basketContainer']//div[@class='button action right basketCash']//a");
	public static final By btnDeliveryPayment = By.xpath("//div[@class='basketContainer']//div[@class='button action right basketCash']//a[@id='LinkButtonNext']"); 
	public static final By btnDeliveryPayment2 = By.xpath("//div[@class='basketContainer']//div[@class='button action right basketCash']//a[@id='linkButtonNextProxy']//span[@id='Body_MainContent_LabelNext']");
	public static final By btnRadio1 = By.xpath("//div[@id='col1']//table[@id='shippingtable']//p//input[@checked='checked']");
	public static final By btnRadio2 = By.xpath("//div[@class='body choice c1']//table[@id='paymenttable']//p//input[@name='paymentmethod']");
	public static final By btnCompletePayment = By.xpath("//div[@id='payment']//div[@class='buttons']//div[@class='button submit']//input[@type='submit']");
	public static final By btnContinue = By.xpath("//div//input[@id='OkContinue']");		
	public static final By btnStatus=By.xpath("//div[@id='tabs-1']//div[@class='orderList']//fieldset[@class='orderLines'][1]/table//tbody[1]//tr[1]//td[@class='short'][4]//img");
	public static final By btnSearch =By.xpath("//div[@id='page']//div//input[@id='Body_ReplaceMainContent_btnShowOrder']");
	public static final By btnSearch2 =By.xpath("//div[@class='filter-smaller']//div[@id='show-search']//input[@id='Search']");
	public static final By btnSelectCorrectProduct=By.xpath("//div[@id='productContainer']//div[@class='product-item'][@1@]//div[@class='product simple small productBlock']//a//span[contains(text(),'Velg')]");
	public static final By btnSave = By.xpath("//div[@class='button action right floatRight basketCash']//button");
	public static final By btnSelectAcessories = By.xpath("//div[@class='product simple medium'][1]//div[@class='footer']//div[@class='button action']//a");
	public static final By btnFindOrders= By.xpath("//div[@class='actionfield']//div[@class='form']//fieldset[@class='container']//fieldset[@class='floatLeft']//input[@name='filterproducts-btnSearch']");
	public static final By btnClose= By.xpath("//div[@id='fancybox-outer']//a[@id='fancybox-close']");
	public static final By btnProceed= By.xpath("//div[@class='colgroup']//div[@class='wizard']//div[@class='next-page']//input[@name='next']");
	public static final By btnProceed2= By.xpath("//div[@class='colgroup']//div[@class='wizard']//div[@class='next-page-top']//input[@name='next']");
	public static final By btnSaveChanges= By.xpath("//div[@class='wizard']//div[@class='next-page']//input[@id='wizardSave']");
	public static final By btnUpdateStore= By.xpath("//div[@class='product']//div[@class='listcontent']//form//input[@name='UpdateSalespoint']");
	public static final By btnEditStore2= By.xpath("//div[@class='next-page-top']//form//input[@name='Rediger']");
	public static final By btnEditStore= By.xpath("//div[@class='form']//form//input[@value='Rediger butikk']");
	public static final By btnEditSynonym= By.xpath("//div[@class='form']//form//input[@value='Rediger synonymer for produktsøk']");
	public static final By btnEditCustomer= By.xpath("//div[@class='wizard']//div[@class='next-page-top']//input[@name='Rediger']");
	public static final By btnLevel3= By.xpath("//div[@class='main-content']//ul[@id='ThirdLevel']//li//button[@id='after3']");
	public static final By btnEditMobile= By.xpath("//div[@class='form']//input[@name='edit']");
	public static final By btnViewCategories= By.xpath("//div[@class='list-products']//div[@class='product']//div[@class='form']//form[12]//input");
	public static final By btnCompletePush= By.xpath("//div[@class='content']//input[@class='standardbutton']");
	public static final By btnEditSupplier= By.xpath("//div[@class='list-products']//div[@class='product'][last()]//div[@class='form']//input[@class='standardbutton']");
	public static final By btnSeeAgent= By.xpath("//div[@class='list-products']//div[@class='product'][1]//div[@class='form']//form//input[@value='Se agent']");
	public static final By btnForHandler= By.xpath("//div[@class='wizard']//div[@class='next-page-top']//form//input[@value='Opprett forhandler']");
	public static final By btnEditProduct = By.xpath("//div[@class='list-products']//div[@class='product'][1]//div[@class='form']//form//input[@value='Rediger produkt']");
	public static final By btnEditUtvalg = By.xpath("//div[@class='list-products']//div[@class='product'][1]//div[@class='form']//form//input[@value='Rediger utvalg']");
	public static final By btnLeveringMeToOrder = By.xpath("//div[@class='wizard']//div[@class='next-page-top']//form//input[@value='Leveringsmetoder']");
	public static final By btnSeeForHandler= By.xpath("//div[@class='list-products']//div[@class='product'][1]//div[@class='form']//form[1]//input[@value='Se forhandler']");
	public static final By btnCreateStore= By.xpath("//div[@class='wizard']//div[@class='next-page-top']//form//input[@value='Opprett butikk']");
	public static final By btnOk= By.xpath("//div[@id='searchResult']//p//input[@value='Velg']");
	public static final By btnPopUpWindowSearch= By.xpath("//div[@class='form']//fieldset//input[@id='searchButton']");
	public static final By btnTransferProducts= By.xpath("//div[@class='content']//form//input[@value='Overfør alle produkter, abo og suppliers til frontend']");
	public static final By btnTransferProductsOnly= By.xpath("//div[@class='content']//form//input[@value='Overfør alle produkter til frontend']");
	public static final By btnProductOverride= By.xpath("//div[@class='form']//form//input[@value='Produktoverstyring']");
	public static final By btnUpdater= By.xpath("//div[@class='main-content']//input[@value='Oppdater']");
	public static final By btnUpdaterButikk= By.xpath("//input[@value='Oppdater butikk']");
	public static final By btnAccesoryTab= By.xpath("//div[@id='tabsfacet']//ul//li//h4[contains(text(),'tilbehør')]");
	public static final By btnUtvalgSearch= By.xpath("//div[@id='show-search']//input[@id='searhButton']");
	public static final By btnImageUpload= By.xpath("//div[@class='img-menu']//div[@class='thumbnail-upload']//input[@name='uploadImage']");
	public static final By btnExistingProducts= By.xpath("//div[@class='mini-basket_body']//div[@class='mini-basket_items']//div[@class='mini-basket_items_i']//div[@class='mini-basket_items_price']//input[@class='mini-basket_items_remove']");
	public static final By btnRemoveProducts= By.xpath("//div[@class='mini-basket_body']//div[@class='mini-basket_items']//div[@class='mini-basket_items_i'][@1@]//div[@class='mini-basket_items_price']//input[@class='mini-basket_items_remove']");
	public static final By btnApproveIncomingProduct= By.xpath("//div[@class='listcontent']//div[3][@class='form']//input[2][@name='startapproval']");
	public static final By btnApproveExistingProduct= By.xpath("//div[@class='listcontent']//div[2][@class='form']//input[2][@name='startapproval']");
 	public static final By btnApproveIncomingProductClickNxt= By.xpath("//div[@class='abcdefCol']//div[@class='wizard']//div[@class='next-page']//input[@value='Gå videre']");
  	public static final By btnApproveIncomingProductWizardSave= By.xpath("//div[@class='abcdefCol']//div[@class='wizard']//div[@class='next-page-top']//input[@id='wizardSave']");
  	public static final By btnEditSalesProduct= By.xpath("//div[@class='wizard']//div[@class='next-page-top']//form[@method='get']//input[@value='Rediger utsalgsprodukt']");
  	public static final By btnBarCodeCalculate= By.xpath("//div[@class='txtcontent']//table[@class='idkeytable']//tr[5]//td[3]//input[@value='Calculate']");
  	public static final By btnNavisionIntegrationButikk= By.xpath("//div[@class='wizard']//div[@class='next-page-top']//form[16]//input");
  	public static final By btnNavisionIntegration= By.xpath("//div[@class='content']//form//input[1]");
  	public static final By btnReturnOrder= By.xpath("//div[@class='displayFieldset']//fieldset[3]//p[1]//input[1]");
  	public static final By btnSelectLevel2HTC= By.xpath("//div[@class='group brand']//ul[@id='listbrand']//li//label[contains(text(),'HTC')]");
  	public static final By btnSimbaReceipt= By.xpath("//input[@value='Vis kvittering']");
  	public static final By btnSimbaServiceOrderInfo= By.xpath("//input[@id='ButtonFetch']");
  	public static final By btnContinueCheckout= By.xpath("//div[@class='basketCash']//div[@class='button action right']//a");
  	public static final By btnB2bApproverSelect= By.xpath("//div[@id='ufd-container']//div[@class='plain']//div[@class='list-scroll'][1]//ul//li[last()]");
  	public static final By btnB2bNyLogin= By.xpath("//div[@class='main-content']//div[2][@class='form']//fieldset//p[5]//span[2]//input");
  	public static final By btnSave2= By.xpath("//div[@class='form']//input[@value='Lagre']");
  	public static final By btnB2bDeliveryAddressSelect= By.xpath("//div[@id='ufd-container']//div[2]//div[@class='list-scroll']//ul//li[last()]");
  	public static final By btnfaktureringsadresse= By.xpath("//div[@id='billingAddressWrapper']//div[@class='deliveryFrame']//span[@class='ufd plain']//input");
  	public static final By btnleveringsadresse= By.xpath("//div[@id='deliveryAddressWrapper']//div[@class='deliveryFrame']//span[@class='ufd plain']//input");
  	public static final By btnSelectAcessoryCart = By.xpath("//div[@class='group']//div[@class='basket-accessories basket-accessories--opened']//ul[@class='basket-accessories_list']//li[@class='basket-accessory'][1]//div[3]//div[1]//a//span");
  	public static final By btnForhandlerStatus = By.xpath("//div[@class='main-content']//div[@class='form']//p[1]//input[@value='True']");
  	public static final By btnleveringsadresserERP = By.xpath("//div[@class='main-content']//div[2]//fieldset[3]//p//input[1][@id='UseCrmDeliveryAddresses']");
  	public static final By btnHapiHapi = By.xpath("//div[@class='container']//div[3]//button[contains(text(),'Hapi')]");
  	public static final By btnNavisionHapi = By.xpath("//div[@class='container']//div[4]//button[contains(text(),'Navision')]");
  	public static final By btnHapiOrders = By.xpath("//div[@class='container']//div[3]//ul//li//a[contains(text(),'Orders')]");
  	public static final By btnHapiNavB2COrders = By.xpath("//div[@class='container']//div[4]//ul//li//a[contains(text(),'B2C orders')]");
  	public static final By btnHapiOrderSearch = By.xpath("//form[@method='post']//div[@class='floatLeft']//div//button");
  	public static final By btnHapiNavOrderSearch = By.xpath("//form[@method='post']//div[1][@class='floatLeft']//button[@type='submit']");
  	
	// Images
	public static final By imgMobile = By.xpath("//div[@id='productContainer']//div[@class='product-item'][@1@]//div[@class='product simple small productBlock']//div[@class='image imageGrid bombanchor']//a//img");
	public static final By imgPDPMobile = By.xpath("//div[@class='product-images']//div[@class='mainproduct']//span[@class='mainimage']//img");
	public static final By imgMyCartMobile = By.xpath("//div[@class='group']//tr[@class='productgroup']//td[@class='imagecart']//div[@class='image']//a//img");
	public static final By imgConfirmOrderMobile =By.xpath("//div[@class='row step3']//tr[@class='productgroup']//td[@class='imagecart']//div[@class='image']//img");
	public static final By imgBomb =By.xpath("//div[@class='product-images']//div[@class='mainproduct']//span[@class='campaign']//img");
	public static final By imgProductImage=By.xpath("//div[@class='product']//img");
	public static final By imgCampaginImage=By.xpath("//div[@id='lightbox']//div[@class='image clearfix padding-box']//span//img[@alt='Kampanjebilde']");
	public static final By imgMobile2=By.xpath("//div[@id='productContainer']//div[@class='product-item'][2]//div[@class='product simple small productBlock']//div[@class='image imageGrid bombanchor']//a//img[1]");
	public static final By imgTargetImageDisplay=By.xpath("//div[@id='selectionList']//ul//li//div[@class='product']");
	public static final By imgSourceUtvalImage=By.xpath("//div[@id='searchResult']//ul[@id='availableList']//li[1]//div[@class='listcontent']");
	public static final By imgTargetUtvalImage=By.xpath("//div[@id='selectionList']//ul[@id='selectedList']");
	public static final By imgAjaxLoad=By.xpath("//div[@id='completedOrderFilter']//form//div[@class='form']//fieldset[@class='container']//img[@style='display: none;']");
	public static final By imgAjaxLoadHapi=By.xpath("//form[@method='post']//div[2]//img[@alt='Searching']");
	public static final By imgFailedAjaxLoad=By.xpath("//div[@id='failedOrderFilter']//form//div[@class='form']//fieldset[@class='container']//img[@style='display: none;']");
	public static final By imgAjaxLoader=By.xpath("//div[@id='page']//div[@id='rightcolumn']//div[@id='bizTalkStatus']//span");
	public static final By imgJqueryLoad=By.xpath("//div[@id='fancybox-loading'  and @style='display: none;']");
	public static final By imgIconLoader=By.xpath("//div[@class='filter']//div[@class='hidden searchIndicator' and @style='display: none;']");
	public static final By imgIconLoad=By.xpath("//div[@class='main-content']//div[@class='form']//p//span[@id='loader' and @style='display: none;']");
	public static final By imgMobilesList=By.xpath("//div[@id='searchResult']//ul[@id='availableList']//li[1]//img");
	public static final By imgUtvalgIconLoader=By.xpath("//div[@class='filter']//div[@class='simplyFloatLeft hidden searchIndicator' and @ style='display: none;']");
	public static final By imgBombStoreVaidate =By.xpath("//div[@id='productrow']//div[@id='productContainer']//div[@class='product-item']//div[@class='product simple small productBlock']//div[2]//img[2][@id='Body_MainContent_productList_productListRepeater_ctl01_0_campaignImageGrid_0']");

	//Text Box
	public static final By txtWithoutSubscription = By.xpath("//div[@class='product-overview']//div[@id='step-number2']//div[@class='product-overview-content']//h2//span[@class='defaultSubscription']");
	public static final By txtMobilePrice = By.xpath("//div[@class='product-overview']//div[@id='step-number3']//div[@class='product-overview-content']//div[@id='pricebox']//h2//strong//span");
	public static final By txtProductPrice = By.xpath("//div[@class='group']//tr[contains(@class,'productgroup')]//td[@class='pricecart'][2]//strong");
	public static final By txtProductPrice2 = By.xpath("//div[@class='group']//tr[@class='productgroup']//td[@class='pricecart'][1]//strong");
	public static final By txtProductPrice3 = By.xpath("//div[@class='group']//tr[@class='productgroup ']//td[@class='pricecart'][2]//strong");
	public static final By txtMonthlyPrice =By.xpath("//div[@class='group']//tr[@class='productgroup']//td[@class='pricecart'][1]//span//strong");
	public static final By txtShippingPrice = By.xpath("//div[@class='group']//tr[@class='shipping']//td[@class='pricecart']//strong");
	public static final By txtTotalPrice = By.xpath("//div[@class='group']//tr[@class='productgroup']//td[@class='pricecart'][3]//strong");
	public static final By txtPayingPrice = By.xpath("//div[@class='group']//tr[@class='footer']//td[@class='pricecart']//strong");
	public static final By txtPayingPrice2 = By.xpath("//div[@class='row step3']//table//tr[@class='footer']//td[@class='pricecart']//strong");
	public static final By txtFirstName = By.xpath("//div[@class='tab_container']//div[@class='field-medium']//p//input[@id='Body_MainContent_MainContent_PersonaliaControl_Firstname']");
	public static final By txtLastName = By.xpath("//div[@class='tab_container']//input[@id='Body_MainContent_MainContent_PersonaliaControl_Lastname']");
	public static final By txtEmail = By.xpath("//div[@class='tab_container']//input[@id='Body_MainContent_MainContent_PersonaliaControl_Email']");
	public static final By txtAddress = By.xpath("//div[@class='tab_container']//input[@id='Body_MainContent_MainContent_PersonaliaControl_AddressLine1']"); 
	public static final By txtPostalCode = By.xpath("//div[@class='tab_container']//input[@id='Body_MainContent_MainContent_PersonaliaControl_PostalCode']"); 
	public static final By txtPostalPlace = By.xpath("//div[@class='tab_container']//input[@id='Body_MainContent_MainContent_PersonaliaControl_PostalPlace']"); 
	public static final By txtProductName = By.xpath("//div[@class='row step3']//tr[@class='productgroup']//td[@class='headcart formatpricecart']//p//strong"); 
	public static final By txtShippingPrice2 = By.xpath("//div[@class='row step3']//tr[@class='shipping']//td[@class='pricecart']//strong");
	public static final By txtTotalPrice2 = By.xpath("//div[@class='row step3']//tr[@class='footer']//td[@class='pricecart']//strong"); 
	public static final By txtPrice = By.xpath("//div[@class='row step3']//tr[@class='productgroup']//td[@class='pricecart formatpricecart'][2]//strong");	
	public static final By txtPrice2 = By.xpath("//div[@class='row step3']//tr[@class='productgroup']//td[@class='pricecart formatpricecart'][3]//strong");	
	public static final By txtCreditCardNumber = By.xpath("//div[@id='payment']//fieldset//div[@class='row text']//input[@id='ctl00_BodyContentPlaceHolder_PaymentControl_txtCardNumber']");
	public static final By txtCardHolderName = By.xpath("//div[@id='payment']//fieldset//div[@class='row text']//input[@id='ctl00_BodyContentPlaceHolder_PaymentControl_txtCardHolderName']");
	public static final By txtCVCCode = By.xpath("//div[@id='payment']//fieldset//div[@class='row text cvc']//input[@id='ctl00_BodyContentPlaceHolder_PaymentControl_txtCVCCode']");
	public static final By txtOrderStatus = By.xpath("//div[@id='content']//div[@class='row']//p[@id='status']//span//strong//span[contains(@id,'Body_MainContent_ReceiptControl')]");
	public static final By txtOrderId = By.xpath("//div[@id='content']//div[@class='row'][2]//h3//span[contains(@id,'Body_MainContent_ReceiptControl')]");
	public static final By txtBillingAddress = By.xpath("//div[@class='row container']//div[@class='c1 adressconfirm']//ul//li");
	public static final By txtShippingDetails = By.xpath("//div[@class='row container']//div[@class='c1 infoconfirm']//ul//li");
	public static final By txtOrderNumberId =By.xpath("//div[@id='page']//div//input[@id='Body_ReplaceMainContent_txtShowOrder']");
	public static final By txtFakeOrder= By.xpath("//div[@class='displayFieldset']//fieldset[2]//p[1]//input[@type='submit']");
	public static final By txtProcessOrder= By.xpath("//div[@id='page']//div[@class='displayFieldset']//fieldset//p//input[@type='submit'][1]");
	public static final By txtidentityNumber = By.xpath("//div[@class='tab_container']//div[@class='row']//div[@id='Body_MainContent_MainContent_PersonaliaControl_ssnInput']//div[@class='field-short']//p//input[@id='Body_MainContent_MainContent_PersonaliaControl_SSN']");
	public static final By txtPhoneNumber = By.xpath("//div[@class='row']//div[@class='row rowcontainer subscriberselection'][@1@]//div[@class='group']//div[@class='choosenumber']//table//tr[1]//td[3]//div[@class='field-short']//input");
	public static final By txtIHelpOrderStatus = By.xpath("//div[@id='page']//div//table[@id='Body_ReplaceMainContent_gvShowOrderLines']//tbody//tr[2]//td[3]");
	public static final By txtIHelpOrderToAppear =By.xpath("//div[@id='page']//div[2]//fieldset//p//input[@type='submit'][1]");
	public static final By txtAgentName = By.xpath("//div[@class='main-content']//div[@class='form']//p//input[@id='Name']");
	public static final By txtAgentSave = By.xpath("//div[@class='wizard']//div[@class='next-page']//input[@id='wizardSave']");
	public static final By txtEditAgent = By.xpath("//div[@class='wizard']//div[@class='next-page-top']//form//input[@name='Rediger']");
	public static final By txtEditRange = By.xpath("//div[@class='wizard']//div[@class='next-page-top']//form//input[@value='Rediger sortiment']");
	public static final By txtValues = By.xpath("//div[@class='form']//input[@id='Value']");
	public static final By txtProductSearch= By.xpath("//div[@class='filter']//div[@id='show-search']//input[@id='SearchText']");
	public static final By txtSearch = By.xpath("//div[@class='filter']//div[@id='show-search']//input[@id='Search']");
	public static final By txtProductList =By.xpath("//div[@class='list-products']//div[@class='product']//div[@class='listcontent']//h3");
	public static final By txtAdminOrderStatus = By.xpath("//div[@class='text-preview']//table[@class='list-orders infoHead']//tbody//tr//td[5]//p[contains(text(),'Ordren er ok')]");
	public static final By txtAccessoriesList = By.xpath("//div[@class='group']//div[@class='basket-accessories basket-accessories--opened']//ul[@class='basket-accessories_list']//li[@class='basket-accessory']");
	public static final By txtAccessory = By.xpath("//div[@class='group']//div[@class='basket-accessories basket-accessories--opened']//ul[@class='basket-accessories_list']//li[@class='basket-accessory'][1]");
	public static final By txtReference = By.xpath("//div[@class='deliveryFrame']//table[@class='addressTable referenceTable']//input[@class='enforceMaxLength']");
	public static final By txtQuantity= By.xpath("//div[@class='group']//tr[@class='productgroup']//td[@class='pricecart']//input[@class='quantitySelector']");
	public static final By txtSearchOrder=By.xpath("//div[@class='actionfield']//div[@class='form']//fieldset[@class='container']//fieldset[@class='floatLeft']//input[@name='completedsearchString']");
	public static final By txtMobilePrice2=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td[2]//div//strong");
	public static final By txtSubscriptionCount=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='selectablerow ChosenSubscription  selected']");
	public static final By txtNordialogMobilePrice=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td//strong");
	public static final By txtMobilePriceWithoutSubscription=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='selectablerow ChosenSubscription hiddenSubscription selected']//td[2]//div//strong");
	public static final By txtSubscriptionName=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td//div//div//label");
	public static final By txtNordialogSubscriptionName=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td//label");
	public static final By txtWithoutSubscriptionName=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='selectablerow ChosenSubscription hiddenSubscription selected']//td//div//div//label");
	public static final By txtTotalMobilePrice=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td[3]");
	public static final By txtTotalMobilePriceWithoutSubscription=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='selectablerow ChosenSubscription hiddenSubscription selected']//td[3]");
	public static final By txtTotalMobilePrice2=By.xpath("//div[@class='product-overview-content']//div[@id='pricebox']//li//strong//span[@class='totalPrice priceFormat']");
	public static final By txtMannedSPris=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td[4]");
	public static final By txtMannedSPrisWithoutSubscription=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='selectablerow ChosenSubscription hiddenSubscription selected']//td[4]");
	public static final By txtMannedSPris2=By.xpath("//div[@class='subscr-summary']//div[1]");
	public static final By txtMinutesPris=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td[5]//div[@class='info-icon-container']");
	public static final By txtMinutesPris2=By.xpath("//div[@class='subscr-summary']//div[2]//strong");
	public static final By txtDataRatePris=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td[7]//div[@class='info-icon-container']");
	public static final By txtDataRatePris2=By.xpath("//div[@class='subscr-summary']//div[@id='includedData']//strong");
	public static final By txtSmsMms=By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td[6]");
	public static final By txtSMS=By.xpath("//div[@class='subscr-summary']//div[@id='smsPrice']//strong");
	public static final By txtMMS=By.xpath("//div[@class='subscr-summary']//div[@id='mmsPrice']//strong");
	public static final By txtDisplayText=By.xpath("//div[@id='content']//div[@class='head hide']//h1[contains(text(),'Nettbutikk')]");
	public static final By txtProductTotalCount=By.xpath("//div[@class='group brand']//ul//li//h4//span[@class='number']//span[@id='Body_MainContent_productList_totalCount']");
	public static final By txtProductResultCount=By.xpath("//div[@class='row facet']//h2//span[@id='resultCount']");
	public static final By txtWordDisplay=By.xpath("//div[@class='row facet']//h2");
	public static final By txtBillingHeading1=By.xpath("//div[@class='tab_container']//div[@class='field-medium'][1]//label//span");
	public static final By txtBillingHeading2=By.xpath("//div[@class='tab_container']//div[@class='field-medium'][2]//label//span");
	public static final By txtBillingHeading3=By.xpath("//div[@class='tab_container']//div[@class='field-medium'][3]//label//span");
	public static final By txtBillingHeading4=By.xpath("//div[@class='tab_container']//div[@class='field-short']//label//span");
	public static final By txtBillingHeading5=By.xpath("//div[@class='tab_container']//div[@class='field-medium']//label//span[contains(text(),'Adresse')]");
	public static final By txtBillingHeading6=By.xpath("//div[@class='tab_container']//label//span[contains(text(),'Postnr')]");
	public static final By txtBillingHeading7=By.xpath("//div[@class='tab_container']//span[@class='field-medium']//label//span[contains(text(),'Poststed')]");
	public static final By txtMobileCost=By.xpath("//div[@id='Body_RightHandColumnWrap_RightHandColumn_MiniBasketControl_PanelBasket']//ul//li//div[2]//em");
	public static final By txtShippingCost=By.xpath("//div[@id='Body_RightHandColumnWrap_RightHandColumn_MiniBasketControl_PanelBasket']//div[@class='footer']//div[2]//em");
	public static final By txtTotalCost=By.xpath("//div[@id='Body_RightHandColumnWrap_RightHandColumn_MiniBasketControl_PanelBasket']//div[@class='footer']//div[5]//strong");
	public static final By txtShippingcharges=By.xpath("//div[@class='body choice c1']//table[@id='shippingtable']//tr[@class='selected']//td[@class='antiborder2']//h3//span");//updated
	public static final By txtServicePack=By.xpath("//div[@class='body choice c1']//table[@id='shippingtable']//tr[@class='selected']//td[2]//p");
	public static final By txtCreditDetails=By.xpath("//div[@class='body choice c1']//table[@id='paymenttable']//tr[@class='selected']//td[2]//p//strong");
	public static final By txtNameDetails=By.xpath("//div[@class='c1 adressconfirm']//ul//li//span[1]");
	public static final By txtEmailDetails=By.xpath("//div[@class='c1 adressconfirm']//ul//li//span[5]");
	public static final By txtBillingPaymentDetails=By.xpath("//div[@class='c1 infoconfirm']//ul[@class='usp']");
	public static final By txtMobileName=By.xpath("//div[@id='tabs-1']//div[@class='orderList'][1]//fieldset[@class='orderLines'][1]//table//tbody[1]//tr//td[1]");
	public static final By txtSubscriptionType=By.xpath("//div[@id='tabs-1']//div[@class='orderList'][1]//fieldset[@class='orderLines'][1]//table//tbody[2]//tr//td[1]");
	public static final By txtMobileNo=By.xpath("//div[@id='tabs-1']//div[@class='orderList'][1]//fieldset[@class='orderLines'][1]//table//tbody[2]//tr//td[4]");
	public static final By txtMobileNumber=By.xpath("//div[@class='row step3']//table//tbody//tr[@class='productgroup']//td[@class='headcart formatpricecart']//span");
	public static final By txtNordialogNumber=By.xpath("//div[@class='row step3']//table//tbody//tr[@class='productgroup']//td[@class='headcart formatpricecart']//p[2]");
	public static final By txtBannerShippingPrice=By.xpath("//div[@id='Body_RightHandColumnWrap_RightHandColumn_MiniBasketControl_PanelBasket']//div[@class='footer']//div[2]//em");
	public static final By txtBannerShippingPrice1=By.xpath("//div[@class='mini-basket']//div[@class='mini-basket_body']//div[@class='mini-basket_shipping']//div[2]");
	public static final By txtBannerProductPrice=By.xpath("//div[@id='Body_RightHandColumnWrap_RightHandColumn_MiniBasketControl_PanelBasket']//ul//li//div//em");
	public static final By txtBannerProductPrice1=By.xpath("//div[@class='mini-basket_items']//div[@class='mini-basket_items_price']");
	public static final By txtTotalProductCost=By.xpath("//div[@class='text-preview']//table[@class='list-orders infoHead']//tbody//tr//td[5]//p[2]");
	public static final By txtName1=By.xpath("//div[@id='tabs-2']//div[@class='orderList']//fieldset//tbody//tr[2]//td[2]");
	public static final By txtAddress1=By.xpath("//div[@id='tabs-2']//div[@class='orderList']//fieldset//tbody//tr[3]//td[2]");
	public static final By txtPostalCode1=By.xpath("//div[@id='tabs-2']//div[@class='orderList']//fieldset//tbody//tr[4]//td[2]");
	public static final By txtPostalAddress1=By.xpath("//div[@id='tabs-2']//div[@class='orderList']//fieldset//tbody//tr[5]//td[2]");
	public static final By txtName2=By.xpath("//div[@id='tabs-2']//div[@class='orderList']//fieldset//tbody//tr[2]//td[4]");
	public static final By txtAddress2=By.xpath("//div[@id='tabs-2']//div[@class='orderList']//fieldset//tbody//tr[3]//td[4]");
	public static final By txtPostalCode2=By.xpath("//div[@id='tabs-2']//div[@class='orderList']//fieldset//tbody//tr[4]//td[4]");
	public static final By txtPostalAddress2=By.xpath("//div[@id='tabs-2']//div[@class='orderList']//fieldset//tbody//tr[5]//td[4]");
	public static final By txtPostalAddress3=By.xpath("//div[@class='c1 adressconfirm']//ul//li//span[2]");
	public static final By txtPostalCity=By.xpath("//div[@class='c1 adressconfirm']//ul//li//span[3]");
	public static final By txtPaymentMethod=By.xpath("//div[@id='tabs-3']//div[@class='orderList']//fieldset//tbody//td[1]");
	public static final By txtInvoiceNumber=By.xpath("//div[@id='tabs-3']//div[@class='orderList']//fieldset//tbody//td[2]");
	public static final By txtInvoiceStatus=By.xpath("//div[@id='tabs-3']//div[@class='orderList']//fieldset//tbody//td[3]");
	public static final By txtButtik=By.xpath("//div[@class='filter-smaller']//div[@id='show-search']//input[@id='filter_SearchText']");
	public static final By txtSupplierLabel=By.xpath("//div[@class='product']//div[@class='listcontent']//span[@class='supplierlabel']");
	public static final By txtAttributes1=By.xpath("//div[@class='product']//div[@class='listcontent']//div[@class='attributes-highlight']//p//span[7]");
	public static final By txtAttributes2=By.xpath("//div[@class='product']//div[@class='listcontent']//div[@class='attributes-highlight']//p//span[6]");
	public static final By txtFromDate=By.xpath("//div[@id='page']//div//input[@id='Body_ReplaceMainContent_tbExternalChangedFrom']");
	public static final By txtToDate=By.xpath("//div[@id='page']//div//input[@id='Body_ReplaceMainContent_tbExternalChangedTo']");
	public static final By txtAllTasks=By.xpath("//div[@id='taskOverview']//tbody//tr");
	public static final By txtStatusOk=By.xpath("//div[@id='taskOverview']//tbody//tr//td[contains(text(),'OK')]");
	public static final By txtCNETBox=By.xpath("//div[@id='failedOrderFilter']//form[@id='SearchForm']//div//fieldset[@class='container']//input[@id='cnetid']");
	public static final By txtCNETList=By.xpath("//div[@id='searchResult']//div[@class='row']//div//a[@class='cnet']//div");
	public static final By txtTitle=By.xpath("//div[@class='main-content']//li//input[@id='Description']");
	public static final By txtDescription=By.xpath("//div[@class='main-content']//li//textarea[@id='Text']");
	public static final By txtModelName=By.xpath("//div[@class='main-content']//li//input[@id='Modell']");
	public static final By txtCostPrice=By.xpath("//div[@class='main-content']//li//input[@id='CostPrice']");
	public static final By txtWeight=By.xpath("//div[@class='main-content']//li//input[@id='Weight']");
	public static final By txtBarCode=By.xpath("//div[@class='main-content']//li//input[@id='BarCode']");
	public static final By txtSupplierProductId=By.xpath("//div[@class='main-content']//li//input[@id='SupplierProductId']");
	public static final By txtProducerProductId=By.xpath("//div[@class='main-content']//li//input[@id='ProducerProductId']");
	public static final By txtProducerProductUrl=By.xpath("//div[@class='main-content']//li//input[@id='ProducerProductUrl']");
	public static final By txtMessageToHermesText=By.xpath("//div[@class='main-content']//li//textarea[@id='MessageToHermesText']");
	public static final By txtSetValue=By.xpath("//div[@class='form-wizard']//fieldset//input[@id='attributeValue']");
	public static final By txtYoutubeLink=By.xpath("//div[@class='youtubeLink']//input[@id='YoutubeLink']");
	public static final By txtFlashLink=By.xpath("//div[@class='youtubeLink']//input[@id='FlashLink']");
	public static final By txtFlashWidth=By.xpath("//div[@class='youtubeLink']//input[@id='FlashWidth']");
	public static final By txtFlashHeight=By.xpath("//div[@class='youtubeLink']//input[@id='FlashHeight']");
	public static final By txtwizardSave=By.xpath("//div[@class='next-page-top']//input[@id='wizardSave']");
	public static final By txtTitle2=By.xpath("//div[@class='product'][1]//div[@class='listcontent']//h3");
	public static final By txtUserName=By.xpath("//div[@class='form']//p//input[@id='UserName']");
	public static final By txtFirstName2=By.xpath("//div[@class='form']//p//input[@id='FirstName']");
	public static final By txtLastName2=By.xpath("//div[@class='form']//p//input[@id='LastName']");
	public static final By txtEmail2=By.xpath("//div[@class='form']//p//input[@id='Email']");
	public static final By txtMobileNumber2=By.xpath("//div[@class='form']//p//input[@id='MobileNumber']");
	public static final By txtProducts=By.xpath("//div[@class='product'][7]//div[@class='listcontent']//h3");
	public static final By txtServiceUrl=By.xpath("//div[@class='form'][1]//fieldset[1]//p//input[@id='ServiceUrl']");
	public static final By txtField1Descrption=By.xpath("//div[@class='formX']//p//input[@id='fields_0__Description']");
	public static final By txtField2Description=By.xpath("//div[@class='formX']//p//input[@id='fields_1__Description']");
	public static final By txtNewCategory=By.xpath("//div[@class='main-content']//ul[@id='ThirdLevel']//li//input[@id='new0']");
	public static final By txtSubmitCategory=By.xpath("//div[@class='next-page']//p[@class='right']//input[@id='submitCategories']");
	public static final By txtupdateMessage = By.xpath("//div[@class='wizard-message-sucess']//div[@class='message' and contains(text(),'Visningskategorier oppdatert')]");
	public static final By txtSuccessMessage = By.xpath("//div[@class='message-sucess']//h2[contains(text(),'Oppdatering vellykket.')]");
	public static final By txtDeliveryCost = By.xpath("//div[@class='list-products']//div[@class='product'][last()]//div[@class='attributes-highlight'][last()]//li");
	public static final By txtName = By.xpath("//div[@class='main-content']//li[1]//input[@id='Name']");
	public static final By txtPostCode = By.xpath("//div[@class='main-content']//li[2]//input[@id='PostCode']");
	public static final By txtDescription2 = By.xpath("//div[@class='main-content']//li[last()]//textarea[@id='Description']");
	public static final By txtDeliveryPrice = By.xpath("//div[@id='availableShippingmethods']//li[1]//div[@class='selector_item_body']//input[@id='PriceValue_5']");
	public static final By txtKaranteneNumber = By.xpath("//div[@id='ticker']//table[3]//tr//th[last()]//a");
	public static final By txtCompanyName = By.xpath("//div[@class='main-content']//input[@id='CompanyName']");
	public static final By txtCompanyMarketName = By.xpath("//div[@class='main-content']//input[@id='CompanyMarketName']");
	public static final By txtOrganizationNumber = By.xpath("//div[@class='main-content']//input[@id='OrganizationNumber']");
	public static final By txtAddressLine1 = By.xpath("//div[@class='main-content']//input[@id='BronnoysundAddress_AddressAddressLine1']");
	public static final By txtAddressPostalCodeNumber = By.xpath("//div[@class='main-content']//input[@id='BronnoysundAddress_AddressPostalCodeNumber']");
	public static final By txtAddressPostalCodeName = By.xpath("//div[@class='main-content']//input[@id='BronnoysundAddress_AddressPostalCodeName']");
	public static final By txtPhoneNumber2 = By.xpath("//div[@class='main-content']//input[@id='BronnoysundAddress_PhoneNumber']");
	public static final By txtFaxNumber = By.xpath("//div[@class='main-content']//input[@id='BronnoysundAddress_FaxNumber']");
	public static final By txtMainPhoneNumber = By.xpath("//div[@class='main-content']//input[@id='MainPhoneNumber']");
	public static final By txtChiefExecutiveOfficer = By.xpath("//div[@class='main-content']//input[@id='ChiefExecutiveOfficer']");
	public static final By txtBankAccountNumber = By.xpath("//div[@class='main-content']//input[@id='BankAccountNumber']");
	public static final By txtNavisionCompanyId = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='NavisionCompanyId']");
	public static final By txtKhBillingCustomerId = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='KhBillingCustomerId']");
	public static final By txtCrmId = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='CrmId']");
	public static final By txtTelecomputingCompanyId = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='TelecomputingCompanyId']");
	public static final By txtPaymentAccountNumber = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='PaymentAccountNumber']");
	public static final By txtPaymentEncryptionKey = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='PaymentEncryptionKey']");
	public static final By txtTelenorNettforhandlerDealerId = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='TelenorNettforhandlerDealerId']");
	public static final By txtTelenorNettforhandlerDealerIdLocalStore = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='TelenorNettforhandlerDealerIdLocalStore']");
	public static final By txtCreditScore = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='CreditScore']");
	public static final By txtTurnover = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='Turnover']");
	public static final By txtProfitBeforeTax = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='ProfitBeforeTax']");
	public static final By txtLiquidityRatio = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='LiquidityRatio']");
	public static final By txtEquity = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='Equity']");
	public static final By txtResultRatio = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='ResultRatio']");
	public static final By txtCreditCheckPerformedBy = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='CreditCheckPerformedBy']");
	public static final By txtCreditLimitLimit = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='CreditLimitLimit']");
	public static final By txtShopAddressLine1 = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='ShopAddress_AddressAddressLine1']");
	public static final By txtShopAddressPostalCodeNumber = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='ShopAddress_AddressPostalCodeNumber']");
	public static final By txtShopAddressPostalCodeName = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='ShopAddress_AddressPostalCodeName']");
	public static final By txtGeoLocation = By.xpath("//div[@class='main-content']//div[@class='form']//input[@id='GeoLocation']");
	public static final By txtAbout = By.xpath("//div[@class='main-content']//div[@class='form']//textarea[@id='About']");
	public static final By txtDistributor = By.xpath("//div[@id='tabs-1']//div[@class='product'][last()]//h3//a");
	public static final By txtInvoiceNo = By.xpath("//div[@class='displayFieldset']//fieldset[2]//input[1]");
	public static final By txtIMEINo = By.xpath("//div[@class='displayFieldset']//fieldset[2]//input[2]");
	public static final By txtProducerURL = By.xpath("//div[@class='main-content']//li//input[@id='ProducerProductURL']");
	public static final By txtProductTitle = By.xpath("//div[@class='main-content']//div[@class='form']//p// input[@id='Description']");
	public static final By txtUniqueSelling = By.xpath("//div[@class='main-content']//div[@class='form']//p// input[@id='UniqueSellingPointText']");
	public static final By txtFactText = By.xpath("//div[@class='main-content']//div[@class='form']//p// textarea[@id='FactText']");
	public static final By txtName3 = By.xpath("//div[@class='form']//input[@id='Name']");
	public static final By txtDescription1 = By.xpath("//div[@class='form']//textarea[@id='Description']");
	public static final By txtUtvalgTitle = By.xpath("//div[@class='list-products']//div[@class='product'][1]//h3//a");
	public static final By txtEditLastProduct = By.xpath("//div[@class='list-products']//div[@class='product'][last()]//div[@class='form']//form[last()-1]//input");
	public static final By txtProductText = By.xpath("//div[@class='list-products']//div[@class='product'][last()]//div//h3");
	public static final By txtPercentage = By.xpath("//div[@class='form']//input[@id='Percentage']");
	public static final By txtSourceElement = By.xpath("//div[@id='searchResult']//ul//li[1]//div[@class='product']//div[@class='listcontent']");
	public static final By txtTargetElement = By.xpath("//div[@id='selectionList']//ul");
	public static final By txtSourceElement2 = By.xpath("//div[@class='floatLeft dragdrop']//ul[@id='availableList']//li[@class='product'][1]");
	public static final By txtTargetElement2 = By.xpath("//div[@class='floatRight dragdrop']//div[@id='selectionList']//ul");
	public static final By txtSourceElement3 = By.xpath("//ul[@id='availableList']//li[1]//div[@class='product'][1]");
	public static final By txtTargetElement3 = By.xpath("//div[@id='selectionList']//ul");
	public static final By txtSourceElement4 = By.xpath("//div[@class='left dragdrop']//li[1]");
	public static final By txtTargetElement4 = By.xpath("//div[@class='right dragdrop']//div[@id='selectionList']");
	public static final By txtSourceElement5 = By.xpath("//div//ul//li");
	public static final By txtTargetElement5 = By.xpath("//div[@id='selectionList']//ul");
	public static final By txtSourceElement6 = By.xpath("//ul[@id='availableList']//li[@class='product'][1]//div[@class='listcontentLarge']");
	public static final By txtTargetElement6 = By.xpath("//div[@class='floatRight dragdrop']//div[@id='selectionList']//ul[@id='selectedList']");
	public static final By txtSourceElement7 = By.xpath("//div[@class='wizard-body']//div[@class='left dragdrop']//div[@id='availableSubscriptions']//ul[1]//li[1]");
	public static final By txtTargetElement7 = By.xpath("//div[@id='rightdragdrop']//div[@class='dragdrop']//div[@id='selectionList']//ul[1]");
	public static final By txtOrganizationNo = By.xpath("//div[@class='form']//fieldset//input[@name='orgnr']");
	public static final By txtInvoiceHeader = By.xpath("//div[@class='form']//fieldset//input[@name='InvoiceHeader']");	
	public static final By txtInvoiceText = By.xpath("//div[@class='form']//fieldset//textarea[@name='InvoiceText']");
	public static final By txtPriceValue = By.xpath("//div[@class='selector_item_body']//input[@id='PriceValue_8']");
	public static final By txtCreditLimit = By.xpath("//div[@class='form']//input[@id='CreditLimit']");
	public static final By txtProductSearch2 = By.xpath("//div[@class='filter']//div[@id='show-search']//input[@id='searchString']");
	public static final By txtProductUSP = By.xpath("//div[@class='form']//input[@id='ProductUsp']");
	public static final By txtProductDescription = By.xpath("//div[@class='form']//textarea[@id='ProductFacts']");
	public static final By txtTelenorProductUSP = By.xpath("//div[@class='row rowcontainer']//div[@class='head']//h2");
	public static final By txtTelenorProductDescription = By.xpath("//div[@class='row rowcontainer']//div[@class='body']//span");
	public static final By txtDjuiceShippingPrice = By.xpath("//div[@class='footer']//div[2]");
	public static final By txtStoreSelect= By.xpath("//div[@class='b2b-userinfo_select']//span//input");
	public static final By txtUtenbind1= By.xpath("//div[@class='product-overview']//div[@id='step-number2']//div[@class='product-overview-content'][1]//span[@class='defaultBinding']");
	public static final By txtUtenbind2= By.xpath("//div[@class='body']//table[@id='subscription-table']//tr[1]//select//option");
	public static final By txtSubscriberSelection= By.xpath("//div[@class='choosenumber']//span[@class='ufd plain']//input");
	public static final By txtInvoicePrice= By.xpath("//div[@id='col1']//table[@id='shippingtable']//tr[@class='selected']//td[@class='antiborder2']//h3//span");
	public static final By txtSupplierName= By.xpath("//div[@class='list-products']//div[@class='product'][last()]//h3");
	public static final By txtBillingDetails= By.xpath("//div[@class='c1 adressconfirm']//ul//li[1]");
	public static final By txtDeliveryDetails= By.xpath("//div[@class='c1 adressconfirm']//ul//li[2]");
	public static final By txtInvoice= By.xpath("//div[@class='c1 infoconfirm']//ul//li[2]//strong//span");
	public static final By txtSpace= By.xpath("//div[@class='selector']//li[2]//div[@class='selector_item_head'][1]");
	public static final By txtMobileList= By.xpath("//div[@id='productContainer']//div[@class='product-item']//div[@class='product simple small productBlock']//a//span[@class='displayName']");
	public static final By txtPaymentDetailsPrice= By.xpath("//div[@id='ordersummary']//table//tbody//tr[@class='price']//td//span");
	public static final By txtPhoneName = By.xpath("//div[@class='product']//div[@class='listcontent']//h3");
	public static final By txtSubscriptionList = By.xpath("//div[@id='productContainer']//div[@class='product-item']//div[@class='product simple small productBlock']//div[@class='head']//h2//a//div[@class='subscriptionNameContainer']");
	public static final By txtSimbaConsentPhone = By.xpath("//div[@id='Body_MainContent_MainContent_PersonaliaControl_PanelUserSections']//div[@id='consentPhoneNumber']//input[@id='consent_phone_number']");
	public static final By txtCreatedAgent = By.xpath("//div[@class='colgroup']//div[@class='abcdefCol']//div[@class='wizard-title']//h3");
	public static final By txtBarCodeInput = By.xpath("//div[@class='txtcontent']//table[@class='idkeytable']//tbody[1]//tr[5]//td[2]//input[@class='itemref']");
	public static final By txtBarCodeResult = By.xpath("//div[@class='txtcontent']//table[@class='idkeytable']//tbody[1]//tr[5]//td[5]//input[@name='result_number']");
	public static final By txtEditAgentSubscription = By.xpath("//div[@class='wizard']//div[@class='next-page-top']//form//input[@value='Rediger abonnement']");
	public static final By txtSimbaNoConsentMsg = By.xpath("//div[@class='displayFieldset']//ul[1]");
	public static final By txtSalesProductCount = By.xpath("//div[@class='productconnection-list']//div[@class='container']//ul//li[2]//span[2]");
	public static final By txtPreSaleOrderStatus = By.xpath("//div[@id='content']//tbody//tr[7][@class='Error']//td[contains(text(),'Klarte ikke å starte opp det utsatte abonnementet, prøver igjen om 3 timer')]");
	public static final By txtShopNavisionId = By.xpath("//div[@class='main-content']//div[@class='form']//fieldset//p//input[@id='NavisionCustomerId']");
	public static final By txtReceiptFrame = By.xpath("//form[@id='CronusForm']");
	public static final By txtServiceReceiptFrame = By.xpath("//span[@id='LabelFetched']");
	public static final By txtProductCatalogFirst = By.xpath("//div[@class='list-products']//div[1][@class='product']//div[@class='listcontent']//h3");
	public static final By txtProductLimitError1 = By.xpath("//div[@id='Body_MainContent_productDetail_ErrorPanel']//div[@class='error']//h4");
	public static final By txtProductLimitError2 = By.xpath("//div[@id='Body_MainContent_productDetail_ErrorPanel']//div[@class='error']//p");
	public static final By txtAccessoryLimitError1 = By.xpath("//div[@id='body']//div[@id='content']/div[@class='row error errorMessages']//h4");
	public static final By txtAccessoryLimitError2 = By.xpath("//div[@id='body']//div[@id='content']/div[@class='row error errorMessages']//p");
	public static final By txtSharedUserFornavn = By.xpath("//div[@id='content']//div[2][@class='field-medium']//input[@id='Body_MainContent_firstname']");
	public static final By txtSharedUserEtternavn = By.xpath("//div[@id='content']//div[3][@class='field-medium']//input[@id='Body_MainContent_lastname']");
	public static final By txtSharedUserEpost = By.xpath("//div[@id='content']//div[4][@class='field-medium']//input[@id='Body_MainContent_email']");
	public static final By txtB2BApproverlabel = By.xpath("//div[@class='row']//div[@class='deliveryFrame']//tr[2]//td[1]//span");
	public static final By txtB2BApproverSelect = By.xpath("//div[@class='deliveryFrame']//span[@class='ufd plain']//input");
	public static final By txtSynonymLevel2 = By.xpath("//div[2][@class='grd_33']//div[@class='grd_i']//ul//li[1]//input");
	public static final By txtB2BSearchInput = By.xpath("//div[@class='productSearch']//input[@id='sidebarSearchInput']");
	public static final By txtB2BSearchClick = By.xpath("//div[@class='productSearch']//input[@id='inputsearch-submit']");
	public static final By txtB2BSearchProdCount = By.xpath("//div[@id='productContainer']//div[@class='product list productBlock']//div[@class='head']//h2//a//span[@class='displayName']");
	public static final By txtAdminUserCheck = By.xpath("//div[@class='form']//div[@class='product']//div[@class='listcontentLarge']//strong[contains(text(),'@1@')]");
	public static final By txtB2BDeliveryAddressSelect = By.xpath("//div[@id='deliveryAddressWrapper']//div[@class='deliveryFrame']//span[@class='ufd plain']//button");
	public static final By txtB2BDeliveryAddresskontakt = By.xpath("//div[@id='deliveryAddressWrapper']//div[@class='deliveryFrame']//tbody//tr[2]//td[2]//input");
	public static final By txtB2BDeliveryAddressSelskap = By.xpath("//div[@id='deliveryAddressWrapper']//div[@class='deliveryFrame']//tbody//tr[3]//td[2]//input");
	public static final By txtB2BDeliveryAddressAdresse = By.xpath("//div[@id='deliveryAddressWrapper']//div[@class='deliveryFrame']//tbody//tr[4]//td[2]//input");
	public static final By txtB2BDeliveryAddressAdresse2 = By.xpath("//div[@id='deliveryAddressWrapper']//div[@class='deliveryFrame']//tbody//tr[5]//td[2]//input");
	public static final By txtB2BDeliveryAddressPostnummer = By.xpath("//div[@id='deliveryAddressWrapper']//div[@class='deliveryFrame']//tbody//tr[6]//td[2]//input");
	public static final By txtB2BDeliveryAddressPoststed = By.xpath("//div[@id='deliveryAddressWrapper']//div[@class='deliveryFrame']//tbody//tr[7]//td[2]//input");
	public static final By txtDeliveryAddressDropText = By.xpath("//div[@id='ufd-container']//div[2][@class='plain']//div[@class='list-scroll']//ul//li[last()-1]");
	public static final By txtDeliveryAddressSharedUser = By.xpath("//div[@id='ufd-container']//div[1][@class='plain']//div[@class='list-scroll']//ul//li[last()-1]");
	public static final By txtBillingAddressDropText = By.xpath("//div[@id='ufd-container']//div[3][@class='plain']//div[@class='list-scroll']//ul//li[last()-1]");
	public static final By txtBillingAddressSharedUser = By.xpath("//div[@id='ufd-container']//div[2][@class='plain']//div[@class='list-scroll']//ul//li[last()-1]");
	public static final By txtHapiOrderSearch = By.xpath("//form[@method='post']//div[@class='floatLeft']//div[1]//input");
	public static final By txtHapiOrderStatus = By.xpath("//div[@id='result']//table//tbody//tr[2]//td[contains(text(),'Completed')]");

	//CheckBox
	public static final By chkTermsConditions = By.xpath("//div[@class='choice']//table//input[@id='Body_MainContent_MainContent_ConfirmOrderControl_AcceptTerms']");		
	public static final By chkKeepSameNumber = By.xpath("//div[@class='group']//div[@class='choosenumber']//table//tr[1]//td[@class='modeSelector']//input[@class='use_own_number use_new_or_old_number']");
	public static final By chkShipping = By.xpath("//div[@id='col1']//table[@id='shippingtable']//input[@value='2PILOT']");
	public static final By chkBilling = By.xpath("//div[@class='body choice c1']//table[@id='paymenttable']//input[@name='paymentmethod']");
	public static final By chkNewNumber = By.xpath("//div[@class='group']//div[@class='choosenumber']//table//tr[2]//td[@class='modeSelector']//input[@class='use_new_number use_new_or_old_number']");
	public static final By chkSubscription = By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//th//input[@checked='checked']");
	public static final By chkNordialogSubscription = By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='@1@']//td//input");
	public static final By chkWithoutSubscription = By.xpath("//div[@class='productDetails']//table[@id='subscription-table']//tbody//tr[@class='selectablerow ChosenSubscription hiddenSubscription selected']//th//input[@checked='checked']");
	public static final By chkCampagin = By.xpath("//div[@class='product'][1]//div[@class='form campaign']//li//label[@class='Kampanje']");
	public static final By chkLevel3 = By.xpath("//div[@class='main-content']//ul[@id='thirdLevel']//li[last()]//input[1]");
	public static final By chkStoreLevel3 = By.xpath("//div[@class='selector']//li[1]//div[@class='selector_item_body']//div[@class='select-tags'][2]//ul//li[last()]//input[2]");
	public static final By chkServicePack = By.xpath("//div[@id='availableShippingmethods']//li[1]//div[@class='selector_item_head']//input[@class='selector_item_selected']");
	public static final By chkVoice = By.xpath("//div[@class='main-content']//ul//li[contains(text(),'Bedrift (B)')]//input[1]");
	public static final By chkIPhoneVoice = By.xpath("//div[@id='subscription-types']//ul[2]//li[2]//input[1]");
	public static final By chkInvoice = By.xpath("//div[@class='body choice c1']//table[@id='paymenttable']//td[@class='antiborder1']//p//input[@name='paymentmethod']");
	public static final By chkAllowDeliveryAddress = By.xpath("//div[@class='main-content']//input[@id='AllowCustomDeliveryAddress']");
	public static final By chkItemSelector = By.xpath("//div[@class='selector_item_head']//input[1]");
	public static final By chkBillingAddress = By.xpath("//div[@class='form']//input[@id='ChooseBillingAddress']");
	public static final By chkPaymentMode=By.xpath("//div[@class='wizard-body']//div[@class='main-content']//div[@class='form']//p//input[@id='PaymentMethodTypeCreditCard']");
	public static final By chkLevel1 = By.xpath("//div[@class='main-content']//ul[@id='topLevel']//input[@checked='checked']");
	public static final By chkLevel1MobiltBreradBand = By.xpath("//div[@class='main-content']//ul[@id='topLevel']//li[3]//input[@class='topLevel']");
	public static final By chkDescriptionselected1 = By.xpath("//div[@class='formX']//p[1]//input[@checked='checked']");
	public static final By chkDescription1 = By.xpath("//div[@class='formX']//p[1]//input[@type='checkbox'][1]");
	public static final By chkDescriptionselected2 = By.xpath("//div[@class='formX']//p[2]//input[@checked='checked']");
	public static final By chkDescription2 = By.xpath("//div[@class='formX']//p[2]//input[@type='checkbox'][1]");
	public static final By chkLevels = By.xpath("//div[@class='selector']//li[1]//div[@class='selector_item_head'][1]//input");
	public static final By chkCampaign = By.xpath("//div[@class='product'][@1@]//div[@class='listcontent']//div[@class='form campaign']//li[3]//input[@type='radio']");
	public static final By chkApproveProductLevel1 = By.xpath("//div[@class='wizard']//div[@class='wizard-body']//div[@class='left']//ul[@id='topLevel']//li[2]//input[@class='topLevel']");
	public static final By chkApproveProductLevel2 = By.xpath("//div[@class='wizard']//div[@class='wizard-body']//div[@class='left']//ul[2][@id='secondLevel']//li[9]//input[@class='secondLevel']");
	public static final By chkPresaleProduct = By.xpath("//div[@class='main-content']//ul//li[17]//span[2]//input[@value='True']");
	public static final By chkAddSubscriptionB2B = By.xpath("//div[1][@id='additionalSubscriptionServices']//table[@class='checkout-table no-zebra']//tr[2]//input");
	public static final By chkBBAddSubscriptionB2B = By.xpath("//div[2][@id='additionalSubscriptionServices']//table[@class='checkout-table no-zebra']//tbody//tr[3]//input");
	public static final By chkAllLeveringsadresserERP = By.xpath("//div[@class='container']//div[@style='margin-left:20px']//input[@id='SelectAllAddresses']");

	//Combo Boxes
	public static final By cmbExpiryMonth = By.id("ctl00_BodyContentPlaceHolder_PaymentControl_ddExpireMonth");
	public static final By cmbExpiryYear = By.id("ctl00_BodyContentPlaceHolder_PaymentControl_ddExpireYear");
	public static final By cmdListBox= By.xpath("//div[@id='sortinglist']//dl[@id='dropdownbinding']");
	public static final By cmdHomePageListBox1= By.xpath("//div[@id='sortinglist']//dl[@id='Body_MainContent_productList_abmsort']");
	public static final By cmdHomePageListBox2= By.xpath("//div[@id='sortinglist']//dl[@id='price-sort']");
	
	//Link Text
    public static final By lnkTextAdminLink = By.linkText("Admin");
    public static final By lnkTextProductLink = By.linkText("Produkt");
    public static final By lnkTextButikkLink = By.linkText("Butikk");
    
    
    //CSS Locators 
    
    public static final By lnkAddingCategories = By.cssSelector("a[href='/Admin/Categories']");
    public static final By lnkSubMenuProductCatalog = By.cssSelector("a[href='/Product/ShowList']");
    public static final By lnkSubMenuButikk = By.cssSelector("a[href='/Salespoint/ShowList']");
    public static final By lnkSubMenuTransferShop = By.cssSelector("a[href='/Admin/TransferToWebshop']");
}
